(function(){
const tools=[
 ['Word Counter','Count words, characters, sentences, paragraphs and reading time.','tools/word-counter.html','🔢'],
 ['Character Counter','Count characters with and without spaces.','tools/character-counter.html','🔤'],
 ['Line Counter','Count total, non-empty and unique lines.','tools/line-counter.html','📏'],
 ['Word Frequency Counter','See how often each word appears in your text.','tools/word-frequency-counter.html','📊'],
 ['Case Converter','Convert text to upper, lower, title and sentence case.','tools/case-converter.html','Aa'],
 ['Text Cleaner','Remove extra spaces, blank lines and common clutter.','tools/text-cleaner.html','🧹'],
 ['Small Text Generator','Turn normal text into compact Unicode small text.','tools/small-text-generator.html','ᵃᵇ'],
 ['Superscript Generator','Convert text to superscript Unicode characters.','tools/superscript-generator.html','ˣ²'],
 ['Subscript Generator','Convert text to subscript Unicode characters.','tools/subscript-generator.html','ₓ₂'],
 ['Remove Duplicate Lines','Remove repeated lines while preserving order.','tools/remove-duplicate-lines.html','♻️'],
 ['Find and Replace','Find text and replace it throughout your content.','tools/find-and-replace.html','🔎'],
 ['Text to Slug','Create clean URL-friendly slugs from text.','tools/text-to-slug.html','🔗'],
 ['Lorem Ipsum Generator','Generate placeholder paragraphs for layouts and mockups.','tools/lorem-ipsum-generator.html','📝'],
 ['Random Text Generator','Generate random words and placeholder text.','tools/random-text-generator.html','🎲']
];
window.TEXTTOOLS=tools;
function header(){const page=document.body.dataset.page||'';const active=x=>page===x?'active':'';const base=/\/(tools|blog)\//.test(location.pathname)?'../':'';if(localStorage.getItem('tt-light')==='true')document.documentElement.classList.add('light');document.getElementById('site-header').innerHTML=`<div class="site-header"><div class="container nav"><a class="brand" href="${base}index.html"><span class="brand-mark" aria-hidden="true">T</span><span>Text<strong>Tools</strong></span></a><nav class="nav-links" id="primary-navigation" aria-label="Main navigation"><a class="${active('home')}" href="${base}index.html">Home</a><a class="${active('all')}" href="${base}index.html#tools">All Tools</a><a class="${active('categories')}" href="${base}index.html#tools">Categories</a><a class="${active('blog')}" href="${base}blog.html">Blog</a><a class="${active('about')}" href="${base}about.html">About Us</a><a class="${active('contact')}" href="${base}contact.html">Contact Us</a></nav><div class="nav-actions"><button class="theme-btn" id="themeToggle" type="button" aria-label="Switch to light theme" title="Switch theme">☼</button><a class="btn btn-primary" href="${base}index.html#tools">Explore Tools</a><button class="mobile-toggle" id="mobileToggle" type="button" aria-controls="primary-navigation" aria-expanded="false" aria-label="Open navigation">☰</button></div></div></div>`;const b=document.getElementById('themeToggle'),menuButton=document.getElementById('mobileToggle'),nav=document.getElementById('primary-navigation');const updateThemeButton=()=>{const light=document.documentElement.classList.contains('light');b.textContent=light?'☾':'☼';b.setAttribute('aria-label',`Switch to ${light?'dark':'light'} theme`);b.title=`Switch to ${light?'dark':'light'} theme`};updateThemeButton();b.onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('tt-light',document.documentElement.classList.contains('light'));updateThemeButton()};const closeMenu=()=>{nav.classList.remove('is-open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open navigation');menuButton.textContent='☰'};menuButton.onclick=()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';nav.classList.toggle('is-open',open);menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation':'Open navigation');menuButton.textContent=open?'×':'☰'};nav.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});window.addEventListener('resize',()=>{if(window.innerWidth>950)closeMenu()})}
function footer(){const f=document.getElementById('site-footer'),base=/\/(tools|blog)\//.test(location.pathname)?'../':'';if(f)f.innerHTML=`<div class="site-footer"><div class="container footer-inner"><div>© ${new Date().getFullYear()} TextTools. Free browser-based text utilities.</div><div class="footer-links"><a href="${base}about.html">About</a><a href="${base}blog.html">Blog</a><a href="${base}privacy.html">Privacy</a><a href="${base}terms.html">Terms</a><a href="${base}contact.html">Contact</a></div></div></div>`}
function search(){const input=document.getElementById('toolSearch'),box=document.getElementById('searchResults');if(!input||!box)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(!q){box.classList.remove('show');return}const m=tools.filter(t=>(t[0]+' '+t[1]).toLowerCase().includes(q)).slice(0,7);box.innerHTML=m.length?m.map(t=>`<a href="${t[2]}">${t[3]} <strong>${t[0]}</strong><br><small>${t[1]}</small></a>`).join(''):'<div class="search-empty">No matching tool found.</div>';box.classList.add('show')});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))box.classList.remove('show')})}
function init(){header();footer();search()}document.addEventListener('DOMContentLoaded',init);})();
